### ISSUE TITLE
setup_channels with cross_sections_type="xyzpoints" causes an assertion error

### ISSUE THREAD

**Issue by rvnooyen** [Deltares/hydromt_delft3dfm#110]
### Version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version.

### Reproducible Example

Use of the method setup_channels with cross_sections_type="xyzpoints" as per documentation gives an assertion error (see below in current behaviour)
Use of the method setup_channels with cross_sections_type="point" also gives an assertion error (see below in current behaviour)

### Current behaviour

 cross_sections_type="xyzpoints" -> File "C:\Users\Ronald\anaconda3\envs\qgis\lib\site-packages\hydromt_delft3dfm\dflowfm.py", line 1201, in _setup_crosssections
    raise NotImplementedError(
NotImplementedError: Method xyzpoints is not implemented.

 cross_sections_type="point"  -> File "C:\Users\Ronald\anaconda3\envs\qgis\lib\site-packages\hydromt_delft3dfm\dflowfm.py", line 323, in setup_channels
    assert {crosssections_type}.issubset({"xyzpoints", "branch"})
AssertionError

### Desired behaviour

acceptance of cross_sections_type="point" and cross_sections_type="xyz"

**Comment by shartgring** [comment]
This issue has been fixed in PR #131
