### ISSUE TITLE
User guide installation guide conda argument incorrect

### ISSUE THREAD

**Issue by xldeltares** [Deltares/hydromt_delft3dfm#122]
### Version checks

- [X] I have checked that the issue still exists on the latest versions

### Kind of issue

Docs are wrong

### Documentation problem

conda create -n hydromt-delft3dfm -c conda-forge hydromt

**Comment by veenstrajelmer** [comment]
This was resolved in https://github.com/Deltares/hydromt_delft3dfm/pull/157
