### ISSUE TITLE
Typo in setup_manholes parameters

### ISSUE THREAD

**Issue by robertgroenewege** [Deltares/hydromt_delft3dfm#126]
### Version checks

- [X] I have checked that the issue still exists on the latest versions

### Kind of issue

Docs are wrong

### Documentation problem

One of the parameters in the documentation is "manholes_defaults_fn". This should be "manhole_defaults_fn", based on the source code.

Docs: https://deltares.github.io/hydromt_delft3dfm/latest/_generated/hydromt_delft3dfm.DFlowFMModel.setup_manholes.html

**Comment by veenstrajelmer** [comment]
@robertgroenewege thanks for reporting this, it will be resolved in the next release.
