### ISSUE TITLE
Improve handling of closed cross-sections

### ISSUE THREAD

**Issue by shartgring** [Deltares/hydromt_delft3dfm#146]
### Version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version.

### Reproducible Example

The current code does not support good handling of closed cross-sections. They should be formatted differently in the resulting crsdef.loc: "no" and "yes" instead of 0 and 1

### Current behaviour

closed: "no" and "yes"

### Desired behaviour

closed: 0 and 1

**Comment by hboisgon** [comment]
Hydromt released new versions of the artifact_data catalog yesterday so I decided to fix it in a more advanced PR: #151 
Once it's merged this should fix your tests. I'll have a look and review then.
