### ISSUE TITLE
align dflowfm_build.yml between testdata and examples

### ISSUE THREAD

**Issue by xldeltares** [Deltares/hydromt_delft3dfm#171]
### Version checks

- [X] I have checked that the issue still exists on the latest versions

### Kind of issue

Docs are wrong

### Documentation problem

In tests/data/dflowfm_build_local.yml and tests/data/dflowfm_build.yml, the [global] section is missing. It would be better to make it more explicit as an example of how to use the yml file correctly.  Similar to that, some of the default arguments can be added to the yml file too. 

Needs to check if this should also be added to the example notebooks.

**Comment by veenstrajelmer** [comment]
dflowfm_build.yml are not identical between tests/data and example, align this. Furthermore, the `test_model_build_local_code` misses the `setup_bridges` and `setup_culverts` steps.

Follow up in: https://github.com/Deltares/hydromt_delft3dfm/issues/177
