### ISSUE TITLE
typo in allowed columns for setup_pipes

### ISSUE THREAD

**Issue by jeroenwinkelhorst** [Deltares/hydromt_delft3dfm#173]
### Version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version.

### Reproducible Example

`fm.setup_pipes(region={"geom": "input/region.shp"}, pipes_fn=fn_conduit_preproc, friction_type="Manning")`

`fn_conduit_preproc` contains pipe geometry with the columns ['branchid', 'width', 'height', 'invlev_up', 'invlev_dn',
       'frictionvalue', 'shape', 'geometry']

### Current behaviour

column invlev_dn is dropped and replace with a default value

### Desired behaviour

use the values in the column invlev_dn

### Additional context

variable _allowed_columns contains a type "inlev_dn" should be "invlev_dn"

**Comment by veenstrajelmer** [comment]
@jeroenwinkelhorst could you share a reproducible example that shows the unexpected behavior? That makes it easier to debug and we could also directly add it as a test upon fixing the bug.

**Comment by jeroenwinkelhorst** [comment]
Hi Jelmer, an reproducable example is too much effort for this small bug. In https://github.com/Deltares/hydromt_delft3dfm/blob/main/hydromt_delft3dfm/dflowfm.py in the function `setup_pipes()` you must change the last value in the _variable `_allowed_columns`

```
        # filter for allowed columns
        br_type = "pipe"
        _allowed_columns = [
            "geometry",
            "branchid",
            "branchtype",
            "branchorder",
            "material",
            "spacing",
            "branchid",
            "frictionvalue",
            "shape",  # circle or rectangle
            "diameter",  # circle
            "width",  # rectangle
            "height",  # rectangle
            "invlev_up",
            "inlev_dn",
        ]
```

```
        # filter for allowed columns
        br_type = "pipe"
        _allowed_columns = [
            "geometry",
            "branchid",
            "branchtype",
            "branchorder",
            "material",
            "spacing",
            "branchid",
            "frictionvalue",
            "shape",  # circle or rectangle
            "diameter",  # circle
            "width",  # rectangle
            "height",  # rectangle
            "invlev_up",
            "inlvev_dn",
        ]
```

**Comment by veenstrajelmer** [comment]
Helpful, thanks, I guess you meant `invlev_dn` instead of `inlvev_dn` right?
