### ISSUE TITLE
Arrange automatic linking to HydroMT-Delft3D FM project board

### ISSUE THREAD

**Issue by rhutten** [Deltares/hydromt_delft3dfm#31]
### Kind of request

Adding new functionality

### Enhancement Description

When creating an issue not project is set. In addition, the status is missing. This is something we would like to add. 

### Use case

Everytime you create an issue!
![image](https://github.com/Deltares/hydromt_delft3dfm/assets/55204099/339f68ac-9df0-466d-bbe7-10dbe1de0974)

**Comment by rhutten** [comment]
The changes below are directly made in the main on the Github page:

Via the projectboard we were able to set some workflows:

1. Auto-add to project --> All issues are automatically set to HydroMT-Delft3D FM project board.
2. Item added to project --> All issues set to the project board get automatically the status: Backlog

We changed the label given to issue in templates slightly to make sure that the correct label is given to each issue.

**Comment by xldeltares** [comment]
check
