### ISSUE TITLE
Remove pygeos dependency

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/hydromt_delft3dfm#37]
### Version checks

- [X] I have checked that the issue still exists on the latest versions

### Kind of issue

Docs are wrong

### Documentation problem

I miss a "task" issue form, so I used the documentation form instead.

The installation of pygeos results in warnings when using geopandas:
```
DeprecationWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas still uses PyGEOS by default. However, starting with version 0.14, the default will switch to Shapely. To force to use Shapely 2.0 now, you can either uninstall PyGEOS or set the environment variable USE_PYGEOS=0.
```

In the toml file, a comment already mentions to remove it when the new xugrid is out, which is now available (0.6.1): https://github.com/Deltares/hydromt_delft3dfm/blob/main/pyproject.toml#L20

Therefore, the pygeos dependency can be removed.

Also, the toml file states `"shapely >=0.2.0"`, I think this should be "shapely >=2.0.0"

**Comment by rhutten** [comment]
@veenstrajelmer could pick-up this issue somewhere in the next 2 weeks?
