### ISSUE TITLE
Extend basic documentation

### ISSUE THREAD

**Issue by rhutten** [Deltares/hydromt_delft3dfm#7]
**What is the need for this task.**
We started a new HydroMT-Github repository and this needs documentation. 

**What is the task?**
- Setup basic documentation in README.rst.
- Setup getting started: installation guide, user guide, API reference, example

**Comment by xldeltares** [comment]
Notes on installation guide (developer):
1. make a new environment  ```conda env create -f envs\hydromt-delft3dfm```
2. install hydromt-delft3dfm ```flit install --pth-file"
3. test the working environment with ```hydromt --models```

Notes on running the example:
1. navigate to tests\data folder
2. to build test model from local data ```hydromt build dflowfm local -r "{'geom': './local_data/1D_extent.geojson'}" -i dflowfm_build_local.ini -d test_data.yaml --fo -vvv```
3. to build piave model from global data ```hydromt build dflowfm piave -r "{'bbox': [12.4331, 46.4661, 12.5212, 46.5369]}" -i dflowfm_build.ini --dd --fo -vvv```

**Comment by veenstrajelmer** [comment]
Alternatively one could install in an existing model like this:
- `conda install gdal -c conda-forge` (gdal is not pip installable)
- `pip install -e .[test,doc]` (local install as developer, from the checkout directory)
- Or as a user: `pip install git+https://github.com/Deltares/hydromt_delft3dfm`
- optionally install branch Helene: `pip install git+https://github.com/Deltares/hydromt/tree/mesh_model`

**Comment by xldeltares** [comment]
Add in readme.rst: https://github.com/Deltares/hydromt_delft3dfm/issues/20
