### ISSUE TITLE
update requirements in pyproject.toml

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/hydromt_delft3dfm#88]
### Version checks

- [X] I have checked that the issue still exists on the latest versions

### Kind of issue

Docs are wrong

### Documentation problem

We might need a "task" issue template also, since the current templates do not cover what I will write down here.

There is still an open TODO in [pyproject.toml](https://github.com/Deltares/hydromt_delft3dfm/blob/main/pyproject.toml) about the supported python versions. Since meshkernel 2.1.0 was released a while ago, we can now support python 3.11. It is also important to update meshkernel since this is very much in development and it is good to keep up to date.

When looking at the dependencies in pyproject.toml, I recommend several requirement updates:
- meshkernel <=2.0.2 should be >2.1.0 (see above)
- shapely >=0.2.0, probably should be >=2.0.0
- xugrid had significant updates, I recommend to require xugrid >=0.6.4 (latest)
- add support for python 3.11, both in [line 27](https://github.com/Deltares/hydromt_delft3dfm/blob/62aff87ac5237c81e13cc5e9551f268deb6c4c95/pyproject.toml#L27) as [line 38](https://github.com/Deltares/hydromt_delft3dfm/blob/62aff87ac5237c81e13cc5e9551f268deb6c4c95/pyproject.toml#L38)

I also think we should expand the testbank to py 3.8, py 3.10 and py 3.11, it currently only tests py 3.9.

**Comment by xldeltares** [comment]
- meshkernel upgrade depends on the link1d2d improvement issue: https://github.com/Deltares/hydromt_delft3dfm/issues/90
- shapely was a typo, fixed in the branch linked to this issue.
- xugrid is already using 0.6.4, therefore added in the pyproject.toml
- python 3.11 could not be supported yet due to meshkernel version
